trigger:
- 'main'

variables:
  buildConfiguration: 'Release'
  repo: 'rootofevil2009/raceposting'
  tag: '$(Build.BuildId)'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: 'dockerhub'
    - task: Docker@2
      displayName: 'Build image'
      inputs:
        command: buildAndPush
        repository: $(repo)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 'dockerhub'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Logout from ACR
      inputs:
        command: logout
        containerRegistry: 'dockerhub'
- stage: 'DeployToStage'
  displayName: 'Deploy the container'
  dependsOn: Build
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool: 'ExternalVMs'
    variables:
    - group: Stage
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: 'dockerhub'
    - task: Bash@3
      inputs:
       targetType: filePath
       filePath: ./runcontainer 
       arguments: $(name) $(repo):$(tag) $(fb_token) $(fb_page) $(input) $(archive)
    - task: Docker@2
      displayName: Logout from ACR
      inputs:
        command: logout
        containerRegistry: 'dockerhub'
- stage: 'DeployToProd'
  displayName: 'Deploy the container to Prod'
  dependsOn: DeployToStage
  jobs:
  - job: 'Deploy'
    displayName: 'Deploy job'
    pool: 'ExternalVMs'
    variables:
    - group: Prod
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: 'dockerhub'
    - task: Bash@3
      inputs:
       targetType: filePath
       filePath: ./runcontainer 
       arguments: $(name) $(repo):$(tag) $(fb_token) $(fb_page) $(input) $(archive)
    - task: Docker@2
      displayName: Logout from ACR
      inputs:
        command: logout
        containerRegistry: 'dockerhub'