trigger:
- 'main'

variables:
  buildConfiguration: 'Release'
  repo: 'raceposting'
  tag: '$(Build.BuildId)'

stages:
- stage: 'Build'
  displayName: 'Build and push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: 'dockerhub'
    - task: Docker@2
      displayName: 'Build and push the image to container registry'
      inputs:
        command: buildAndPush
        buildContext: $(Build.Repository.LocalPath)
        repository: $(repo)
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: 'dockerhub'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: logout
        containerRegistry: 'dockerhub'
#- stage: 'Deploy'
#  displayName: 'Deploy the container'
#  dependsOn: Build
#  jobs:
#  - job: 'Deploy'
#    displayName: 'Deploy job'
#    pool:
#      vmImage: 'ubuntu-18.04'
#    variables:
#    - group: Release
#    steps:
#    - task: AzureWebAppContainer@1
#      inputs:
#       appName: $(WebAppName)
#       azureSubscription: 'Resource Manager - Tailspin - Space Game'
#       imageName: $(RegistryName)/$(webRepository):$(build.buildId)